sudo: required
services:
  - docker
before_install:
  - docker build -t  sandeepmunu/docker-react -f Dockerfile.Dev .
script:
  - docker run sandeepmunu/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-sandeep"
  env: "DockerSandeep-env"
  bucket_name: "elasticbeanstalk-ap-south-1-013773653211"
  bucket_path: "docker-sandeep"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: "$aws_secret_key"
